### ISSUE TITLE
A JavaScript Error occured in the main process

### ISSUE THREAD

**Issue by DGrunow** [erikrichardlarson/unbox#26]
First: I love the new UI and the options you can choose from! <3 Thanks for that!

This is my error window:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/z5/zfh080gs4653dv1jrnc_xzqh0000gn/T/AppTranslocation/4C9327B1-CA95-4C35-9474-F1675FBD42B7/d/unbox.app/Contents/Resources/app/src/config.json'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at IpcMainImpl.<anonymous> (/private/var/folders/z5/zfh080gs4653dv1jrnc_xzqh0000gn/T/AppTranslocation/4C9327B1-CA95-4C35-9474-F1675FBD42B7/d/unbox.app/Contents/Resources/app/src/index.js:271:10)
    at IpcMainImpl.emit (events.js:223:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8161)
    at WebContents.emit (events.js:223:5)
```

I get it that it's read-only, but it's not unbox, that folder is read&write...

How can I solve this issue?

Cheers for your hard work on that awesome project!

PS.: Using unbox here: [www.twitch.tv/dannygrunowofficial](www.twitch.tv/dannygrunowofficial)

**Comment by DGrunow** [comment]
Given all the files and folders in the .app read&write rights... not working :/

**Comment by Nass86** [comment]
Yes this only fixed when I moved the app into the Applications Folder. all good now!

**Comment by erikrichardlarson** [comment]
@DGrunow thanks for using! looking great on your channel!

**Comment by DGrunow** [comment]
Moved the folder including the app to the desktop, it's the same... also doing so if I move it to the applications folder :/

**Comment by erikrichardlarson** [comment]
Interesting, so if you just move the application on its own to the desktop, and run from there, it still throws this error?

**Comment by DGrunow** [comment]
Then:

`Uncaught Exception:
Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1306:16)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1442:7)
    at Function.listen (/Users/dannygrunow/Desktop/unbox.app/Contents/Resources/app/node_modules/connect/index.js:217:24)
    at PlayHistory.startServer (/Users/dannygrunow/Desktop/unbox.app/Contents/Resources/app/src/index.js:431:23)
    at App.createWindow (/Users/dannygrunow/Desktop/unbox.app/Contents/Resources/app/src/index.js:733:24)
    at App.emit (events.js:223:5)`

**Comment by Nass86** [comment]
Hmm. Try closing, deleting all copies except in Application folder and restarting and definitely opening it from the Applications folder?

**Comment by erikrichardlarson** [comment]
Oh yeah that usually means another instance is still open, or the port didn't close on the last opened instance. Try closing all running instances and restarting.

**Comment by DGrunow** [comment]
Ah, had the other app open... now its working fine YEAH

SOLVED
