### ISSUE TITLE
Javascript error mac version

### ISSUE THREAD

**Issue by Johnf2021** [erikrichardlarson/unbox#32]
When opening the app and getting the options to choose the software, as soon as I select 'Rekordbox DB' I get a javascript error:

Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/9d/3b_75sn5571_97f7gk73_ltr0000gp/T/AppTranslocation/7B741CC5-E040-4AB7-AC13-44487304E758/d/unbox.app/Contents/Resources/app/src/config.json'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at IpcMainImpl.<anonymous> (/private/var/folders/9d/3b_75sn5571_97f7gk73_ltr0000gp/T/AppTranslocation/7B741CC5-E040-4AB7-AC13-44487304E758/d/unbox.app/Contents/Resources/app/src/index.js:271:10)
    at IpcMainImpl.emit (events.js:223:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8161)
    at WebContents.emit (events.js:223:5)

When I then select a layout (eg. ASOT) I get the same JS error.

From here it all works fine though so just wanted to let you know.

The Windows version doesn't have this problem.

**Comment by erikrichardlarson** [comment]
Yeah so on Mac this happens when the app is in your downloads folder, if you move to your desktop or applications folder it should work, lmk if that doesn't work.

**Comment by Johnf2021** [comment]
I moved the folder into documents and ran it and same thing unfortunately. Like I say, it is working if I just skip past those JS errors.

**Comment by erikrichardlarson** [comment]
Gotcha, can you try your desktop or applications folder?

**Comment by Johnf2021** [comment]
Just tried putting in both applications folder and desktop then opening, same JS error I'm afraid.

**Comment by erikrichardlarson** [comment]
Interesting, can you move the application itself and not the entire folder? That may work, lmk if it doesn't.

**Comment by zehv** [comment]
Hi There - I am having a similar issue on my mac - I moved the application out of downloads to applications and am still getting this. 

Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/Will/Library/Application Support/Pioneer/rekordboxAgent/storage/options.json'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at PlayHistory.getRecentTracks (/Applications/unbox.app/Contents/Resources/app/src/index.js:646:35)
    at PlayHistory.persistHistory (/Applications/unbox.app/Contents/Resources/app/src/index.js:702:10)
    at Timeout._onTimeout (/Applications/unbox.app/Contents/Resources/app/src/index.js:757:28)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by erikrichardlarson** [comment]
@zehv This usually happens because Rekordbox 6 isn't installed, what version of RB do you have?

**Comment by alexmakin** [comment]
Same error, happens before I even open RB, v 6.5.0

Error: EROFS: read-only file system, open '/private/var/folders/jk/pxtv0jcx3xd1pg1kppj24nlc0000gn/T/AppTranslocation/3F1920F2-7AEC-4AFF-90A7-915C91C04EE0/d/unbox.app/Contents/Resources/app/src/config.json'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at IpcMainImpl.<anonymous> (/private/var/folders/jk/pxtv0jcx3xd1pg1kppj24nlc0000gn/T/AppTranslocation/3F1920F2-7AEC-4AFF-90A7-915C91C04EE0/d/unbox.app/Contents/Resources/app/src/index.js:271:10)
    at IpcMainImpl.emit (events.js:223:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8161)
    at WebContents.emit (events.js:223:5)

**Comment by erikrichardlarson** [comment]
This is a different error actually that happens on Mac, try putting the app on your desktop or in your documents folder and running it from there, lmk if that doesn’t work.

**Comment by alexmakin** [comment]
> 
> 
> This is a different error actually that happens on Mac, try putting the app on your desktop or in your documents folder and running it from there, lmk if that doesn’t work.
@erikrichardlarson,

Yep, no luck extracted to either folder.

The error doesn't stop the app from functioning overall tho

macOS 10.15.7

**Comment by erikrichardlarson** [comment]
So try taking the unbox app inside the folder after it was extracted to your downloads, and drag only the app onto your desktop. You want the unbox app standalone not the folder. This shouldddd work, lmk if it doesn’t.

**Comment by alexmakin** [comment]
Bingo! Thanks

Quick follow up question, it takes about 80sec for unbox to display the track information from switching the MASTER track in RB, is this the behavior we should expect to predict?

**Comment by erikrichardlarson** [comment]
Yeah that’s a RB limitation on Mac right now, you can use KUVO to get around this
