### ISSUE TITLE
M1 Mac issue “unbox” is damaged and can’t be opened.

### ISSUE THREAD

**Issue by cojacplays** [erikrichardlarson/unbox#52]
I get this message when I'm initially attempting to get the app open after download. My permissions on System and Security are set to "anyone" and I tried the previous version but Java issues popped up every time I made an attempt to click anything. Is there any current documentation pertaining to M1 issues that I missed?

Here's the message from the previous version:: 

Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/jg/r4h95n9176g7l90p3hqzdn780000gn/T/AppTranslocation/A0F86864-C80A-436A-A727-26E65096A15E/d/unbox.app/Contents/Resources/app/src/config.json'
at Object.openSync (fs.js:440:3)
at Object.func [as openSync] (electron/js2c/asar.js:140:31)
at Object.writeFileSync (fs.js:1265:35)
at IpcMainImpl.<anonymous> (/private/var/folders/jg/r4h95n9176g7l90p3hqzdn780000gn/T/AppTranslocation/A0F86864-C80A-436A-A727-26E65096A15E/d/unbox.app/Contents/Resources/app/src/index.js:374:10)
at IpcMainImpl.emit (events.js:223:5)
at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8161)
at WebContents.emit (events.js:223:5)

**Comment by erikrichardlarson** [comment]
Yoo thanks for using unbox, for the first issue I was able to bypass this by running this in the terminal: "xattr -d com.apple.quarantine /path/to/application/unbox.app" where the path is updated to the path of unbox on your machine. 

For the second issue here you just need to unbox.app in your Applications folder. 

Let me know if you still have issues here.
