### ISSUE TITLE
Will not open on mac

### ISSUE THREAD

**Issue by grillah** [erikrichardlarson/unbox#58]
When I try to open 9.0 on my mac it gives an error "unbox" is damaged and can't be opened. I also tried 8.2 as mentioned in one of the other issues here and it did open but gave javascript errors when I tried to choose RekordboxDB.

Macbook Pro M1 with Big Sur 11.6

**Comment by grillah** [comment]
Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/3x/ztdpxphx31z14lbld0mln85m0000gn/T/AppTranslocation/F52BDDAC-F531-488D-868B-D6D8F5BD48F6/d/unbox.app/Contents/Resources/app/src/config.json'
at Object.openSync (fs.js:440:3)
at Object.func [as openSync] (electron/js2c/asar.js:140:31)
at Object.writeFileSync (fs.js:1265:35)
at IpcMainImpl.<anonymous> (/private/var/folders/3x/ztdpxphx31z14lbld0mln85m0000gn/T/AppTranslocation/F52BDDAC-F531-488D-868B-D6D8F5BD48F6/d/unbox.app/Contents/Resources/app/src/index.js:374:10)
at IpcMainImpl.emit (events.js:223:5)
at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8161)
at WebContents.emit (events.js:223:5)

**Comment by grillah** [comment]
I run my Rekordbox database on an external drive so perhaps that's the issue?

**Comment by erikrichardlarson** [comment]
Ah for this you just need to place the app in your applications folder or on your desktop, lmk if that doesn't work.
