### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by djmel88** [erikrichardlarson/unbox#6]
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/djmelodie/Library/Application Support/Pioneer/rekordboxAgent/storage/options.json'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at PlayHistory.getRecentTracks (/private/var/folders/4v/lvj1zyfd1q3g3pyzbl3215wr0000gn/T/AppTranslocation/F5268397-194D-4198-B615-19BD213463F2/d/unbox.app/Contents/Resources/app/src/index.js:299:35)
    at PlayHistory.persistHistory (/private/var/folders/4v/lvj1zyfd1q3g3pyzbl3215wr0000gn/T/AppTranslocation/F5268397-194D-4198-B615-19BD213463F2/d/unbox.app/Contents/Resources/app/src/index.js:344:10)
    at Timeout._onTimeout (/private/var/folders/4v/lvj1zyfd1q3g3pyzbl3215wr0000gn/T/AppTranslocation/F5268397-194D-4198-B615-19BD213463F2/d/unbox.app/Contents/Resources/app/src/index.js:393:28)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by erikrichardlarson** [comment]
Are you on rekordbox 6? Usually this happens when rekordbox 6 isn't installed. If not, can you search for "rekordboxAgent" on your computer and see where the directory is located?

**Comment by djmel88** [comment]
I have rekordbox 6 installed.  I searched for "rekordboxAgent" and it is no where to be found on my computer

**Comment by erikrichardlarson** [comment]
oh interesting, what version of 6 are you on? 6 should include the rekordboxAgent directory written about here: https://rekord.cloud/blog/technical-inspection-of-rekordbox-6-and-its-new-internals

**Comment by djmel88** [comment]
You are right, the version was 5.  I opened the correct rekordbox 6 and it works not.  Thank you for an awesome app!  Cheers :)

**Comment by erikrichardlarson** [comment]
Thank you!
